export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[];
export type Database={public:{Tables:{
 workspaces:{Row:{id:string;name:string;currency:string;created_by:string;created_at:string};Insert:never;Update:never;Relationships:[]};
 memberships:{Row:{workspace_id:string;user_id:string;role:"owner"|"manager"|"viewer";created_at:string};Insert:never;Update:never;Relationships:[]};
 clients:{Row:{id:string;workspace_id:string;name:string;company:string;email:string|null;phone:string|null;created_at:string;updated_at:string;archived_at:string|null;version:number};Insert:{id?:string;workspace_id:string;name:string;company?:string;email?:string|null;phone?:string|null;created_at?:string;updated_at?:string;archived_at?:string|null;version?:number};Update:{name?:string;company?:string;email?:string|null;phone?:string|null;archived_at?:string|null;version?:number};Relationships:[]};
 inquiries:{Row:{id:string;workspace_id:string;client_id:string;title:string;description:string;source:"website"|"telegram"|"referral"|"other";status:"new"|"contacted"|"proposal"|"won"|"lost";amount_minor:number;assignee_id:string|null;next_contact_on:string|null;created_at:string;updated_at:string;closed_at:string|null;archived_at:string|null;version:number};Insert:{id?:string;workspace_id:string;client_id:string;title:string;description?:string;source:"website"|"telegram"|"referral"|"other";status?:"new"|"contacted"|"proposal"|"won"|"lost";amount_minor?:number;assignee_id?:string|null;next_contact_on?:string|null;created_at?:string;updated_at?:string;closed_at?:string|null;archived_at?:string|null;version?:number};Update:{client_id?:string;title?:string;description?:string;source?:"website"|"telegram"|"referral"|"other";status?:"new"|"contacted"|"proposal"|"won"|"lost";amount_minor?:number;assignee_id?:string|null;next_contact_on?:string|null;closed_at?:string|null;archived_at?:string|null;version?:number};Relationships:[]};
 notes:{Row:{id:string;workspace_id:string;inquiry_id:string;author_id:string;body:string;created_at:string};Insert:{id?:string;workspace_id:string;inquiry_id:string;author_id:string;body:string;created_at?:string};Update:never;Relationships:[]};
 audit_events:{Row:{id:number;workspace_id:string;inquiry_id:string|null;actor_id:string|null;action:string;entity_type:string;entity_id:string;metadata:Json;created_at:string};Insert:never;Update:never;Relationships:[]}
};Views:Record<string,never>;Functions:{bootstrap_workspace:{Args:{workspace_name:string};Returns:string};list_workspace_members:{Args:{wid:string};Returns:{user_id:string;email:string;role:"owner"|"manager"|"viewer"}[]};list_team_members:{Args:{wid:string};Returns:{user_id:string;email:string;role:"owner"|"manager"|"viewer";created_at:string}[]};list_team_invitations:{Args:Record<string,never>;Returns:{id:string;workspace_id:string;workspace_name:string;email:string;role:"manager"|"viewer";expires_at:string}[]};invite_team_member:{Args:{wid:string;invite_email:string;invite_role:"manager"|"viewer"};Returns:string};accept_team_invitation:{Args:{invitation_id:string};Returns:string};revoke_team_invitation:{Args:{wid:string;invitation_id:string};Returns:undefined};change_team_member_role:{Args:{wid:string;member_id:string;expected_role:"manager"|"viewer";new_role:"manager"|"viewer"};Returns:undefined};remove_team_member:{Args:{wid:string;member_id:string;expected_role:"manager"|"viewer"};Returns:undefined}};Enums:{member_role:"owner"|"manager"|"viewer";inquiry_status:"new"|"contacted"|"proposal"|"won"|"lost";inquiry_source:"website"|"telegram"|"referral"|"other";audit_action:string};CompositeTypes:Record<string,never>}};
