"use client";
/* eslint-disable react-hooks/set-state-in-effect -- hydration reads an external browser-only store; persistence failure is surfaced to the user */
import { useEffect, useMemo, useRef, useState } from "react";
import { allowedTransitions, clientSchema, inquirySchema, metrics, money, type DemoState, type Inquiry, type InquiryStatus } from "@/lib/domain";
import { event, loadDemo, saveDemo, seed } from "@/lib/demo";

type View = "overview" | "inquiries" | "clients" | "activity";
const labels: Record<InquiryStatus,string>={new:"Новая",contacted:"Контакт",proposal:"Предложение",won:"Выиграна",lost:"Проиграна"};
const nav:[View,string][]=[["overview","Обзор"],["inquiries","Заявки"],["clients","Клиенты"],["activity","Активность"]];
export function DemoApp(){
 const [state,setState]=useState<DemoState>(seed),[ready,setReady]=useState(false),[view,setView]=useState<View>("overview"),[query,setQuery]=useState(""),[filter,setFilter]=useState<InquiryStatus|"all"|"archive">("all"),[selected,setSelected]=useState<string|null>(null),[modal,setModal]=useState<"inquiry"|"client"|"reset"|null>(null),[toast,setToast]=useState(""); const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const result=loadDemo(localStorage);setState(result.state);if(result.warning)setToast(result.warning);setReady(true)},[]);
 useEffect(()=>{if(ready){const warning=saveDemo(localStorage,state);if(warning)setToast(warning)}},[state,ready]);
 useEffect(()=>{const h=(e:KeyboardEvent)=>{const field=e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement;if((e.key==="/"||e.code==="Slash")&&!field){e.preventDefault();searchRef.current?.focus()}if((e.key.toLowerCase()==="n"||e.code==="KeyN")&&!field)setModal("inquiry");if(e.key==="Escape"){setModal(null);setSelected(null)}};addEventListener("keydown",h);return()=>removeEventListener("keydown",h)},[]);
 const m=useMemo(()=>metrics(state),[state]),clientName=(id:string)=>state.clients.find(c=>c.id===id)?.name??"Без клиента";
 const visible=useMemo(()=>state.inquiries.filter(i=>filter==="archive"?i.archivedAt:!i.archivedAt&&(filter==="all"||i.status===filter)).filter(i=>`${i.title} ${state.clients.find(c=>c.id===i.clientId)?.name??""} ${i.description}`.toLowerCase().includes(query.toLowerCase())),[state,filter,query]);
 const update=(id:string,fn:(i:Inquiry)=>Inquiry,summary:string)=>setState(s=>({...s,inquiries:s.inquiries.map(i=>i.id===id?fn(i):i),audit:[event("inquiry_updated",summary,id),...s.audit]})); const detail=state.inquiries.find(i=>i.id===selected);
 return <div className="shell"><a href="#content" className="skip">К содержимому</a><aside><div className="brand"><span>R</span><strong>Relay</strong></div><nav aria-label="Основная навигация">{nav.map(([id,name])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{name}</button>)}</nav><div className="aside-bottom"><span>Демо-пространство</span><button onClick={()=>setModal("reset")}>Сбросить данные</button></div></aside><main id="content"><div className="demo-banner"><strong>Локальное демо</strong><span>Вымышленные данные. Изменения хранятся только в этом браузере.</span></div><header><div><p className="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО</p><h1>{nav.find(n=>n[0]===view)?.[1]}</h1></div><div className="top-actions"><label className="search"><span>⌕</span><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value.slice(0,100))} placeholder="Поиск…  /" aria-label="Поиск"/></label><button className="primary" onClick={()=>setModal(view==="clients"?"client":"inquiry")}>+ {view==="clients"?"Клиент":"Заявка"}</button></div></header>
 {view==="overview"&&<><section className="metrics"><Metric name="В работе" value={String(m.active)} hint="активные заявки"/><Metric name="Воронка" value={money(m.pipeline)} hint="без архива"/><Metric name="Выиграно" value={money(m.won)} hint="без архива"/><Metric name="Просрочено" value={String(m.overdue)} hint="нужен контакт" attention={m.overdue>0}/></section><section className="panel"><PanelHead title="Ближайшие контакты" action={()=>setView("inquiries")}/><Rows items={state.inquiries.filter(i=>!i.archivedAt&&i.nextContactOn).sort((a,b)=>(a.nextContactOn??"").localeCompare(b.nextContactOn??"")).slice(0,4)} clientName={clientName} onSelect={setSelected}/></section></>}
 {view==="inquiries"&&<section className="panel"><div className="filters">{(["all",...Object.keys(labels),"archive"] as const).map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f as typeof filter)}>{f==="all"?"Все":f==="archive"?"Архив":labels[f as InquiryStatus]}</button>)}</div>{visible.length?<Rows items={visible} clientName={clientName} onSelect={setSelected}/>:<Empty/>}</section>}
 {view==="clients"&&<section className="client-grid">{state.clients.filter(c=>!c.archivedAt&&`${c.name} ${c.company}`.toLowerCase().includes(query.toLowerCase())).map(c=><article key={c.id}><div className="avatar">{c.name.split(" ").map(x=>x[0]).join("")}</div><h2>{c.name}</h2><p>{c.company}</p><dl><dt>Почта</dt><dd>{c.email||"—"}</dd><dt>Телефон</dt><dd>{c.phone||"—"}</dd><dt>Заявок</dt><dd>{state.inquiries.filter(i=>i.clientId===c.id).length}</dd></dl></article>)}</section>}
 {view==="activity"&&<section className="panel activity">{state.audit.map(a=><article key={a.id}><span/><div><strong>{a.summary}</strong><p>{new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(a.createdAt))}</p></div></article>)}</section>}</main><div className="mobile-nav">{nav.map(([id,name])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{name}</button>)}</div>
 {detail&&<div className="overlay" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><section className="drawer" role="dialog" aria-modal="true" aria-labelledby="detail-title"><button className="close" onClick={()=>setSelected(null)} aria-label="Закрыть">×</button><span className={`status ${detail.status}`}>{labels[detail.status]}</span><h2 id="detail-title">{detail.title}</h2><p>{detail.description||"Описание не добавлено."}</p><dl className="detail-list"><dt>Клиент</dt><dd>{clientName(detail.clientId)}</dd><dt>Бюджет</dt><dd>{money(detail.amountMinor)}</dd><dt>Следующий контакт</dt><dd>{detail.nextContactOn??"Не назначен"}</dd></dl>{!detail.archivedAt&&<div className="status-actions"><p>Следующий этап</p>{allowedTransitions[detail.status].map(to=><button key={to} onClick={()=>update(detail.id,i=>({...i,status:to,updatedAt:new Date().toISOString(),version:i.version+1}),`Статус «${detail.title}» изменён: ${labels[to]}`)}>{labels[to]}</button>)}</div>}<Notes state={state} inquiry={detail} setState={setState}/><button className="danger-link" onClick={()=>update(detail.id,i=>({...i,archivedAt:i.archivedAt?null:new Date().toISOString(),version:i.version+1}),detail.archivedAt?"Заявка восстановлена":"Заявка перемещена в архив")}>{detail.archivedAt?"Восстановить из архива":"Переместить в архив"}</button></section></div>}
 {modal==="inquiry"&&<InquiryModal clients={state.clients} onClose={()=>setModal(null)} onSave={i=>{setState(s=>({...s,inquiries:[i,...s.inquiries],audit:[event("inquiry_created",`Создана заявка «${i.title}»`,i.id),...s.audit]}));setModal(null);setToast("Заявка добавлена")}}/>}{modal==="client"&&<ClientModal onClose={()=>setModal(null)} onSave={c=>{setState(s=>({...s,clients:[c,...s.clients]}));setModal(null);setToast("Клиент добавлен")}}/>}{modal==="reset"&&<Confirm onClose={()=>setModal(null)} onConfirm={()=>{setState(structuredClone(seed));setModal(null);setToast("Демо сброшено")}}/>}{toast&&<button className="toast" onClick={()=>setToast("")}>{toast}<span>×</span></button>}</div>
}
function Metric({name,value,hint,attention}:{name:string;value:string;hint:string;attention?:boolean}){return <article className={attention?"attention":""}><span>{name}</span><strong>{value}</strong><small>{hint}</small></article>}
function PanelHead({title,action}:{title:string;action:()=>void}){return <div className="panel-head"><div><p className="eyebrow">В ФОКУСЕ</p><h2>{title}</h2></div><button className="text-link" onClick={action}>Все заявки →</button></div>}
function Rows({items,clientName,onSelect}:{items:Inquiry[];clientName:(id:string)=>string;onSelect:(id:string)=>void}){return <div className="rows">{items.map(i=><button className="row" key={i.id} onClick={()=>onSelect(i.id)}><span className={`status ${i.status}`}>{labels[i.status]}</span><span className="row-title"><strong>{i.title}</strong><small>{clientName(i.clientId)}</small></span><span className="row-date">{i.nextContactOn??"—"}</span><strong className="amount">{money(i.amountMinor)}</strong><span>↗</span></button>)}</div>}
function Empty(){return <div className="empty"><strong>Ничего не найдено</strong><p>Измените поиск или фильтр, либо добавьте новую заявку.</p></div>}
function FormModal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="close" onClick={onClose} aria-label="Закрыть">×</button><p className="eyebrow">RELAY CRM</p><h2 id="modal-title">{title}</h2>{children}</section></div>}
function InquiryModal({clients,onClose,onSave}:{clients:DemoState["clients"];onClose:()=>void;onSave:(i:Inquiry)=>void}){const[error,setError]=useState("");return <FormModal title="Новая заявка" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget),parsed=inquirySchema.safeParse({id:crypto.randomUUID(),clientId:d.get("clientId"),title:d.get("title"),description:d.get("description"),source:d.get("source"),status:"new",amountMinor:Math.round(Number(d.get("amount"))*100),nextContactOn:d.get("date")||null,archivedAt:null,updatedAt:new Date().toISOString(),version:1});if(!parsed.success){setError("Проверьте название, сумму и дату.");return}onSave(parsed.data)}}><label>Название<input name="title" required maxLength={160} autoFocus/></label><label>Клиент<select name="clientId">{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="form-row"><label>Бюджет, ₽<input name="amount" type="number" min="0" max="1000000000" required/></label><label>Связаться<input name="date" type="date"/></label></div><label>Источник<select name="source"><option value="website">Сайт</option><option value="telegram">Telegram</option><option value="referral">Рекомендация</option><option value="other">Другое</option></select></label><label>Описание<textarea name="description" maxLength={5000}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary">Создать заявку</button></form></FormModal>}
function ClientModal({onClose,onSave}:{onClose:()=>void;onSave:(c:DemoState["clients"][number])=>void}){const[error,setError]=useState("");return <FormModal title="Новый клиент" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget),parsed=clientSchema.safeParse({id:crypto.randomUUID(),name:d.get("name"),company:d.get("company"),email:d.get("email"),phone:d.get("phone"),archivedAt:null});if(!parsed.success){setError("Проверьте имя и почту.");return}onSave(parsed.data)}}><label>Имя<input name="name" required autoFocus/></label><label>Компания<input name="company"/></label><label>Почта<input name="email" type="email"/></label><label>Телефон<input name="phone"/></label>{error&&<p className="form-error">{error}</p>}<button className="primary">Добавить клиента</button></form></FormModal>}
function Confirm({onClose,onConfirm}:{onClose:()=>void;onConfirm:()=>void}){return <div className="overlay"><section className="modal confirm" role="alertdialog" aria-modal="true"><h2>Сбросить локальное демо?</h2><p>Все изменения в этом браузере будут заменены исходными вымышленными данными.</p><div><button className="secondary" onClick={onClose}>Отмена</button><button className="danger" onClick={onConfirm}>Сбросить</button></div></section></div>}
function Notes({state,inquiry,setState}:{state:DemoState;inquiry:Inquiry;setState:React.Dispatch<React.SetStateAction<DemoState>>}){const[text,setText]=useState("");return <section className="notes"><h3>Заметки</h3>{state.notes.filter(n=>n.inquiryId===inquiry.id).map(n=><article key={n.id}><p>{n.body}</p><small>{new Date(n.createdAt).toLocaleString("ru-RU")}</small></article>)}<form onSubmit={e=>{e.preventDefault();const body=text.trim();if(!body)return;setState(s=>({...s,notes:[...s.notes,{id:crypto.randomUUID(),inquiryId:inquiry.id,body,createdAt:new Date().toISOString()}],audit:[event("note_added",`Добавлена заметка к «${inquiry.title}»`,inquiry.id),...s.audit]}));setText("")}}><textarea aria-label="Новая заметка" value={text} maxLength={4000} onChange={e=>setText(e.target.value)} placeholder="Добавить контекст…"/><button className="secondary">Добавить заметку</button></form></section>}
