"use server";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createServerSupabase } from "@/lib/supabase/server";
import { readSupabaseEnv } from "@/lib/supabase/env";
export type AuthState={message?:string;error?:string};
const credentials=z.object({email:z.email().max(254),password:z.string().min(8).max(128)});
const strongPassword=z.string().min(8).max(128).refine(v=>/[A-Za-zА-Яа-я]/.test(v)&&/\d/.test(v)&&/[^A-Za-zА-Яа-я0-9]/.test(v),{message:"Пароль должен содержать букву, цифру и специальный символ"});
const signupCredentials=z.object({email:z.email().max(254),password:strongPassword});
export async function login(_:AuthState,formData:FormData):Promise<AuthState>{if(!readSupabaseEnv().configured)return{error:"Supabase не настроен"};const parsed=credentials.safeParse({email:formData.get("email"),password:formData.get("password")});if(!parsed.success)return{error:"Проверьте почту и пароль"};const supabase=await createServerSupabase();const{error}=await supabase.auth.signInWithPassword(parsed.data);if(error)return{error:"Не удалось войти. Проверьте данные или повторите позже."};redirect("/app")}
export async function signup(_:AuthState,formData:FormData):Promise<AuthState>{const env=readSupabaseEnv();if(!env.configured)return{error:"Supabase не настроен"};const parsed=signupCredentials.safeParse({email:formData.get("email"),password:formData.get("password")});if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Проверьте данные"};const supabase=await createServerSupabase();const site=process.env.NEXT_PUBLIC_SITE_URL;const options=site&&z.url().safeParse(site).success?{emailRedirectTo:`${site.replace(/\/$/,"")}/auth/callback?next=/app`}:undefined;const{error}=await supabase.auth.signUp({...parsed.data,options});if(error)return{error:"Не удалось создать аккаунт. Повторите позже."};return{message:"Проверьте почту, чтобы подтвердить аккаунт."}}
export async function forgotPassword(_:AuthState,formData:FormData):Promise<AuthState>{if(!readSupabaseEnv().configured)return{error:"Supabase не настроен"};const parsed=z.email().safeParse(formData.get("email"));if(!parsed.success)return{error:"Введите корректную почту"};const supabase=await createServerSupabase();const site=process.env.NEXT_PUBLIC_SITE_URL;await supabase.auth.resetPasswordForEmail(parsed.data,site?{redirectTo:`${site.replace(/\/$/,"")}/auth/callback?next=/app/recover`}:undefined);return{message:"Если аккаунт существует, инструкция отправлена на почту."}}
export async function updatePassword(_:AuthState,formData:FormData):Promise<AuthState>{if(!readSupabaseEnv().configured)return{error:"Сервис восстановления временно недоступен"};const parsed=strongPassword.safeParse(formData.get("password"));if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Проверьте новый пароль"};const supabase=await createServerSupabase();const{data:{user}}=await supabase.auth.getUser();if(!user)return{error:"Ссылка восстановления недействительна или истекла"};const{error}=await supabase.auth.updateUser({password:parsed.data});if(error)return{error:"Не удалось обновить пароль. Запросите новую ссылку."};redirect("/app")}
export async function logout(){if(!readSupabaseEnv().configured)redirect("/app");const supabase=await createServerSupabase();await supabase.auth.signOut();redirect("/app")}
export async function bootstrapWorkspace(formData:FormData){const parsed=z.string().trim().min(1).max(80).safeParse(formData.get("name"));if(!parsed.success)redirect("/app?setup=invalid");const supabase=await createServerSupabase();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/app");const{error}=await supabase.rpc("bootstrap_workspace",{workspace_name:parsed.data});redirect(error?"/app?setup=failed":"/app")}
